### ISSUE TITLE
Many import bugs when running meaningful integration tests

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-moddle#10]
__Describe the Bug__

Currently we do not run both our roundtrip tests _and_ the TCK tests in a proper manner that verifies whether import warnings are thrown.

Because of that there exists a number of issues that we overlooked so far, e.g. https://github.com/bpmn-io/dmn-moddle/issues/9. I've improved the tests [here](https://github.com/bpmn-io/dmn-moddle/tree/dont-ignore-import-warnings) and you can see the CI failing. 

__Steps to Reproduce__

Run `npm test` or `npm run test:integration` on [`dont-ignore-import-warnings`](https://github.com/bpmn-io/dmn-moddle/tree/dont-ignore-import-warnings) branch to surface the issues.

__Expected Behavior__

Import of diagrams in the TCK works without warnings, unless we have explicit reason to whitelist some of the issues.

__Environment__

- Host (Browser/Node version), if applicable: Any
- OS: Any
- Library version: Any

**Comment by philippfromme** [comment]
# Warnings

*
