### ISSUE TITLE
id missing in elements of drgElement

### ISSUE THREAD

**Issue by rroeneman** [bpmn-io/dmn-moddle#17]
Hi, gratefully using dmn-moddle 9.1.0, however...

When reading from XML (.fromXML), the elements of "drgElement" have an "id" that is different from the XML id attribute.

Those id's seem copied from the 'name' attribute. Possibly the id is not found? 
This is causing issues with ElementReferences.

Tested it with: Decision, InputData, KnowledgeSource, BusinessKnowledgeModel, DecisionService.

Example in ModdleElement:
drgElement[1].id = Klein veld
drgElement[1].name = Klein veld

Expected as per XML:
drgElement[1].id = _kfi3ui1e_dismvoie_decision
drgElement[1].name = Klein veld

However when writing to XML id's are transpiled correctly.

Can this be fixed?
Best, Roeneman

**Comment by philippfromme** [comment]
Can you share the XML that reproduces this issue?

**Comment by rroeneman** [comment]
Thank you for quick reply, please see below

`<dmn:definitions xmlns:dmn="http://www.omg.org/spec/DMN/20180521/MODEL/" xmlns="https://kiegroup.org/dmn/_072FFD32-CEDD-4E1B-AB0E-C9732C732EF5" xmlns:feel="http://www.omg.org/spec/DMN/20180521/FEEL/" xmlns:kie="http://www.drools.org/kie/dmn/1.2" xmlns:dmndi="http://www.omg.org/spec/DMN/20180521/DMNDI/" xmlns:di="http://www.omg.org/spec/DMN/20180521/DI/" xmlns:dc="http://www.omg.org/spec/DMN/20180521/DC/" id="_E05DFC7E-61A5-4533-80F9-BE946942F1D1" name="new-file" typeLanguage="http://www.omg.org/spec/DMN/20180521/FEEL/" namespace="https://kiegroup.org/dmn/_072FFD32-CEDD-4E1B-AB0E-C9732C732EF5">
  <dmn:extensionElements/>
  <dmn:businessKnowledgeModel id="_9714A42A-3E9F-4F8C-A627-CF770DABDB04" name="BusinessKnowledgeModel-1">
    <dmn:extensionElements/>
    <dmn:variable id="_9EB8E5A4-A2DF-4792-9B7D-FEA85BF5C009" name="BusinessKnowledgeModel-1"/>
    <dmn:encapsulatedLogic id="_E083AE97-E6BB-4F2A-B6B8-A976943D1B21" kind="FEEL">
      <dmn:literalExpression id="_6B6BD8A7-5978-4FB2-BC29-EE8E713D9E61">
        <dmn:text/>
      </dmn:literalExpression>
    </dmn:encapsulatedLogic>
  </dmn:businessKnowledgeModel>
  <dmn:inputData id="_78385FCD-53C8-46C1-A404-5E019251C7B0" name="InputData-1">
    <dmn:extensionElements/>
    <dmn:variable id="_E8C6E9B9-A471-4F84-9410-47B4D4F69E7F" name="InputData-1"/>
  </dmn:inputData>
  <dmn:decisionService id="_1D51ACD1-5A29-4187-816E-CF18C148057C" name="DecisionService-1">
    <dmn:extensionElements/>
    <dmn:variable id="_6A0E9FD5-98F0-4716-A5B5-17CBF58DEC84" name="DecisionService-1"/>
  </dmn:decisionService>
  <dmn:knowledgeSource id="_5845D8F3-79AB-4672-BEAE-0C9E4E34A539" name="KnowledgeSource-1" locationURI="">
    <dmn:extensionElements/>
    <dmn:type/>
  </dmn:knowledgeSource>
  <dmn:decision id="_94259F4B-1665-4B0C-A4AA-08E68C940497" name="Decision-1">
    <dmn:extensionElements/>
    <dmn:variable id="_87549A3F-7924-47EA-AA5C-1E305AE4B5F6" name="Decision-1"/>
    <dmn:informationRequirement id="_5FB16892-B2F6-47A3-BD0F-0632893A81B2">
      <dmn:requiredInput href="#_78385FCD-53C8-46C1-A404-5E019251C7B0"/>
    </dmn:informationRequirement>
  </dmn:decision>
  <dmn:textAnnotation id="_316323BD-3E84-404B-BA9C-70750EE8008B" textFormat="text/plain">
    <dmn:text>TextAnnotation-1</dmn:text>
  </dmn:textAnnotation>
</dmn:definitions>`

**Comment by philippfromme** [comment]
Mind formatting the XML so it's readable?

**Comment by rroeneman** [comment]
> Mind formatting the XML so it's readable?

See above, can't send an XML I believe, sorry I'm not so experienced with Github issues panel

**Comment by rroeneman** [comment]
So on a clean setup the unexpected behavior does not occur. Still puzzling how to solve this, DMN.xml is going straight into the .fromXML function, but whatever it is I have to look elsewhere.

Sorry for raising this and thanks again for the quick replies!

**Comment by rroeneman** [comment]
Solved: issue was an older version of dmn-moddle running in the same project (through another package). So possibly a function in the global scope?
