### ISSUE TITLE
Promisify APIs

### ISSUE THREAD

**Issue by StephenOTT** [bpmn-io/dmn-moddle#19]
__What should we do?__

We should upgrade `moddle-xml@9` to use the latest Promise support. Therefore the API of this project has to be promisified as well.

__Why should we do it?__

_Original text_

There seems to be usage of setTimeout() in 8.x of moddle-xml, which causes issues in non-browser and non-node execution envs.  The usage seems to have been removed from the 9x version of of moddle-xml.  

Is there a timeline for dmn-moddle to be moved to 9.x of moddle-xml?

----

Related to https://github.com/bpmn-io/bpmn-moddle/pull/73

**Comment by pinussilvestrus** [comment]
Thanks for reporting. We don't have a time-plan to migrate `dmn-moddle` to `moddle-xml@9`. We're open to PRs which improve the situation.

The [migration to `bpmn-moddle`](https://github.com/bpmn-io/bpmn-moddle/pull/73/files) can be taken as a role model.

I'll update the issue description a bit to fit our guidelines.

**Comment by MaxTru** [comment]
Will be tackled soon as part of https://github.com/bpmn-io/dmn-js/issues/514
