### ISSUE TITLE
DMN 1.3 support

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-moddle#3]
* [ ] We are able to read and write DMN 1.3 diagrams.
* [ ] Support for DMN 1.3 is released as a new major version

---

Child of https://github.com/bpmn-io/dmn-js/issues/409

**Comment by barmac** [comment]
Work is happening on https://github.com/bpmn-io/dmn-moddle/tree/3-dmn-1-2

**Comment by barmac** [comment]
I pushed on top a simple test case which shows two problems that are blocking me:

1) Inherited property `id` gets serialized as `di:id` in `DMNShape` and `DMNEdge`:
```xml
      <dmndi:DMNShape di:id="_c3e08836-7973-4e4d-af2b-d46b23725c13_s2" dmnElementRef="_2d131943-c513-416b-acc6-6efe8fe01ba4">
        <dc:Bounds height="61" width="154" x="150" y="150" />
        <dmndi:DMNLabel sharedStyle="LS_c3e08836-7973-4e4d-af2b-d46b23725c13_0" />
      </dmndi:DMNShape>
```
What is funny is that it's serialized correctly when I reverse the order of superClasses (which are `[ "di:Shape" (or "diEdge"), "DMNDiagramElement" ]`), but then the children of an element are ordered incorrectly.

2) `DMNStyle` seems to be not parsed at all, at least it's not present in the serialized XML. This leads to dangling reference.

The test case can be run via `npm run test:integration`.

**Comment by nikku** [comment]
Please add local test coverage in the library that clearly reproduces the issue as well as the expected behavior. This helps me to look into the problem.

**Comment by nikku** [comment]
Sketched a solution via https://github.com/bpmn-io/dmn-moddle/commit/a654f58cba535c6c8b397c37093767378ed3e5a3. You should be able to generate that thing, too.

I also added a focused test case (that can easily be `.only`-ed): https://github.com/bpmn-io/dmn-moddle/commit/a654f58cba535c6c8b397c37093767378ed3e5a3#diff-ce4d6c60b3ac348d6d43b814a1945c03R40

Regardless of TCK or not, we should have basic test coverage. Please add it.

**Comment by barmac** [comment]
Thanks! I was writing the test cases and in the meantime you pushed the fix :)

**Comment by barmac** [comment]
It seems to be working correctly. I will finish the tests for the DI where now we have only stubs.

**Comment by barmac** [comment]
Closed via https://github.com/bpmn-io/dmn-moddle/pull/6
