### ISSUE TITLE
Unparseable content dmndi:Size

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-moddle#9]
__Describe the Bug__

I cannot parse an apparently valid DMN diagram that contains a `dmndi:Size` element: 

```xml
<dmn:definitions>
   ...
    <dmndi:DMNDI>
        <dmndi:DMNDiagram id="_a3ebbd98-af09-42f3-9099-4ae2204a1f54_D1">
            <dmndi:Size height="650.0" width="879.0"/>
            ...
```

The DMN TCK [contains a whole bunch of those diagrams](https://github.com/dmn-tck/tck/search?q=dmndi%3Asize&unscoped_q=dmndi%3Asize).

Resulting error: 

```
unparsable content <dmndi:Size> detected
	line: 121
	column: 12
	nested error: unknown type <dmndi:Size>
```

__Steps to Reproduce__

1. Open [test diagram](https://github.com/bpmn-io/dmn-moddle/files/4225325/size.dmn.txt)
2. Enjoy import warning

__Expected Behavior__

The element is supported.

__Environment__

- Host (Browser/Node version), if applicable: Any
- OS: Any
- Library version: `v8.0.0`

**Comment by barmac** [comment]
Will be fixed via https://github.com/bpmn-io/dmn-moddle/tree/dont-ignore-import-warnings
